# Generated by Django 4.2.13 on 2024-05-20 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CUR_UNIT', models.TextField()),
                ('CUR_NM', models.TextField()),
                ('TTB', models.TextField()),
                ('TTS', models.TextField()),
                ('DEAL_BAS_R', models.TextField()),
            ],
        ),
    ]
