# Generated by Django 4.2.13 on 2024-05-21 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fixed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fin_grp_no', models.IntegerField(null=True)),
                ('fin_co_no', models.CharField(max_length=50, null=True)),
                ('kor_co_nm', models.CharField(max_length=50, null=True)),
                ('fixed_code', models.CharField(max_length=50, null=True)),
                ('fixed_name', models.CharField(max_length=50, null=True)),
                ('dcls_month', models.CharField(max_length=50, null=True)),
                ('join_way', models.CharField(max_length=50, null=True)),
                ('mtrt_int', models.TextField(null=True)),
                ('spcl_cnd', models.TextField(null=True)),
                ('join_deny', models.IntegerField(null=True)),
                ('join_member', models.TextField(null=True)),
                ('etc_note', models.TextField(null=True)),
                ('max_limit', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_code', models.CharField(max_length=50, null=True, unique=True)),
                ('installment_name', models.CharField(max_length=50, null=True)),
                ('dcls_month', models.CharField(max_length=50, null=True)),
                ('join_way', models.CharField(max_length=50, null=True)),
                ('mtrt_int', models.TextField(null=True)),
                ('spcl_cnd', models.TextField(null=True)),
                ('join_deny', models.IntegerField(null=True)),
                ('join_member', models.TextField(null=True)),
                ('etc_note', models.TextField(null=True)),
                ('max_limit', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InstallmentOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intr_rate_type_nm', models.CharField(max_length=50, null=True)),
                ('rsrv_type_nm', models.CharField(max_length=50, null=True)),
                ('save_trm', models.CharField(max_length=50, null=True)),
                ('intr_rate', models.FloatField(null=True)),
                ('intr_rate2', models.FloatField(null=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.installment')),
            ],
        ),
        migrations.CreateModel(
            name='FixedOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intr_rate_type_nm', models.CharField(max_length=50, null=True)),
                ('save_trm', models.CharField(max_length=50, null=True)),
                ('intr_rate', models.FloatField(null=True)),
                ('intr_rate2', models.FloatField(null=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.fixed')),
            ],
        ),
    ]
