# Generated by Django 4.2.13 on 2024-05-20 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_fixed_fixed_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixed',
            name='etc_note',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='fixed',
            name='join_deny',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='fixed',
            name='join_member',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='fixed',
            name='mtrt_int',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='fixed',
            name='sqcl_cnd',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='fixedoption',
            name='intr_rate',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='fixedoption',
            name='intr_rate2',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='installment',
            name='etc_note',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='installment',
            name='join_deny',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='installment',
            name='join_member',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='installment',
            name='mtrt_int',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='installment',
            name='sqcl_cnd',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='installmentoption',
            name='intr_rate',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='installmentoption',
            name='intr_rate2',
            field=models.FloatField(null=True),
        ),
    ]
