# Generated by Django 4.2.13 on 2024-05-20 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_fixed_etc_note_alter_fixed_join_deny_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixed',
            name='dcls_month',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fixed',
            name='fixed_code',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='fixed',
            name='fixed_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fixed',
            name='join_way',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fixedoption',
            name='intr_rate_type_nm',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fixedoption',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.fixed'),
        ),
        migrations.AlterField(
            model_name='fixedoption',
            name='save_trm',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='installment',
            name='dcls_month',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='installment',
            name='installment_code',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='installment',
            name='installment_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='installment',
            name='join_way',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='installmentoption',
            name='intr_rate_type_nm',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='installmentoption',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.installment'),
        ),
        migrations.AlterField(
            model_name='installmentoption',
            name='rsrv_type_nm',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='installmentoption',
            name='save_trm',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
