# Generated by Django 4.2.13 on 2024-05-21 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_rename_sqcl_cnd_fixed_spcl_cnd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixed',
            name='fin_co_no',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fixed',
            name='fin_grp_no',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='fixed',
            name='kor_co_nm',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='installment',
            name='fin_co_no',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='installment',
            name='fin_grp_no',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='installment',
            name='kor_co_nm',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
