# Generated by Django 4.2.13 on 2024-05-21 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_fixed_fin_co_no_fixed_fin_grp_no_fixed_kor_co_nm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixed',
            name='fixed_code',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='installment',
            name='installment_code',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
