# Generated by Django 4.2.13 on 2024-05-21 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_fixed_fin_co_no_fixed_fin_grp_no_fixed_kor_co_nm_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='fixed',
            constraint=models.UniqueConstraint(fields=('kor_co_nm', 'fixed_code'), name='kor_co_nm-fixed_code composite key'),
        ),
        migrations.AddConstraint(
            model_name='installment',
            constraint=models.UniqueConstraint(fields=('kor_co_nm', 'installment_code'), name='kor_co_nm-installment_code composite key'),
        ),
    ]
