# Generated by Django 4.2.13 on 2024-05-21 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_fixed_fixed_code_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='fixed',
            name='kor_co_nm-fixed_code composite key',
        ),
        migrations.RemoveConstraint(
            model_name='installment',
            name='kor_co_nm-installment_code composite key',
        ),
    ]
