# Generated by Django 4.2.13 on 2024-05-17 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fixed',
            field=models.ManyToManyField(related_name='member', to='products.fixed'),
        ),
        migrations.AddField(
            model_name='user',
            name='installment',
            field=models.ManyToManyField(related_name='member', to='products.installment'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
